name: 07 - Using expressions
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: [debug] Print start-up data
        if: ${{inputs.debug}} == true
        run: |
          echo "Triggered by: ${{github.event_name}}
          echo "Branch: ${{github.ref}}
          echo "Commit SHA: ${{github.commit_sha}}
          echo "Runner OS: ${{runner.os}}
      - name: [debug] Print when triggered from main
        if: ${{inputs.debug}}==true and ${{github.ref}}=='main'
        run: echo "I was triggered from main"

      - name: Greeting
        run: echo "Hello, world"
