name: 13 - Using Caching

on:  
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
      node-version:
        type: choice
        options: [18.x, 20.x, 21.x]
        default: 20.x
        description: Node Version
        
jobs:
  install_deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    steps:
      - name: Checkout_code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
      - name: Calculate Cache Key
        id: cache-key
        run: |
          echo "CACHE_KEY = deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
      
      - name: Download Cached Dependencies
        uses: actions/cache@v3
        id: cache
        if: ${{inputs.use-cache}}
        with:
          path: 13-caching/react-app/node_modules
          key: ${{steps.cache-key.outputs.CACHE_KEY}}
     
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci

  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: 13-caching/react-app
    needs: install_deps
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
      
      - name: Download Cached Dependencies
        uses: actions/cache@v3
        id: cache
        if: ${{inputs.use-cache}}
        with:
          key: ${{needs.install_deps.outputs.deps-cache-key}}
          path: 13-caching/react-app/node_modules
      - name: Building
        run: |
          npm run build
      - name: Deploying to non prod
        run: echo "Deploying to non Prod"

  
  linting:
    runs-on: ubuntu-latest
    needs: install_deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout_code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}

      - name: Download Cached Dependencies
        uses: actions/cache@v3
        id: cache
        if: ${{inputs.use-cache}}
        with:
          key: ${{needs.install_deps.outputs.deps-cache-key}}
          path: 13-caching/react-app/node_modules

      - name: Testing
        run: |
          npm run test
      - name: Linting
        run: echo "Linting..."
