name: 14 Working with Artifacts
on:
  workflow_dispatch:

env:
  BUILD_ARTIFACT_KEY: app-${{GITHUB.sha}}
  TEST_COVERAGE_KEY: test-coverage-${{GITHUB.SH}}

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Download Cached Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
          path: 14-artifacts/react-app/node_modules
      - name: Install Dependencies
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: npm ci
        
      - name: Unit Tests
        run: npm run test -- --coverage
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: $TEST_COVERAGE_KEY
          path: 14-artifacts/react-app/coverage

        
      - name: Build code
        run: npm run build

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: $BUILD_ARTIFACT_KEY
          path: 14-artifacts/react-app/build

  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download build files
        uses: actions/download-artifact@v4
        with:
          name: $BUILD_ARTIFACT_KEY
          path: 14-artifacts/react-app/build
          
      - name: Show folder structure
        run: ls -R
