name: 17-1 Custom Actions Composite
on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options: [dev, prod]
    
run-name: 17 - 1 Custom Actions Composite | env - ${{ inputs.target-env}}
env:
  working-dir: 17-1-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-dir }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: '20.x'
          working-dir: ${{ env.working-dir }}
      - name: Test
        run: npm test
      - name: Build
        run: npm run build