name: 17 - 3 - Custom Actions - Docker
on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - 'https://www.google.com'
          - 'https://nonexistent.url.test'    
        default: 'https://www.google.com'

      max_trials:
        description: 'Maximum trials until action fails'
        required: false
        default: 10
      delay:
        description: Delay in seconds between trials
        required: false
        default: 5

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{inputs.url}}
          max_trials: ${{ inputs.max_trials }}
          delay: ${{ inputs.delay }}
      - name: Print output from ping url
        run: |
          echo "URL reachable: ${{ steps.ping-url.outputs.url-reachable }}"
