name: 19 - 1 - Managing Concurrency
on: workflow_dispatch

concurrency:
  group: ${{GITHUB.workflow}}-${{GITHUB.git_ref}}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.notreachableurl.com
          max_trials: 20
          delay: 5
  
